language: python
sudo: false
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 .
  - python -m doctest docs.rst
  - coverage run --branch --source inflexion test.py
after_success:
  - coveralls
